# FINALIZE
#
# Finalization of setup.
# Don't overwrite these values manually.

SCRIPT_SHARED_PATH="$(readlink -e "${BASH_SOURCE[0]}")"
SCRIPT_SHARED_NAME="$(basename "$SCRIPT_SHARED_PATH")"
SCRIPT_SHARED_DIR="$(dirname "$SCRIPT_SHARED_PATH")"
SCRIPT_ORIG_PWD="$(pwd -P)"

SCRIPT_MAIN_PATH="$(readlink -e "$0")"
SCRIPT_MAIN_NAME="$(basename "$SCRIPT_MAIN_PATH")"
SCRIPT_MAIN_DIR="$(dirname "$SCRIPT_MAIN_PATH")"
SCRIPT_MAIN_EXE="$(basename "$SCRIPT_MAIN_DIR")/$SCRIPT_MAIN_NAME"

SCRIPT_CURRENT_PATH=$SCRIPT_SHARED_PATH

export SCRIPT_SHARED_PATH
export SCRIPT_SHARED_NAME
export SCRIPT_SHARED_DIR
export SCRIPT_ORIG_PWD

export SCRIPT_MAIN_PATH
export SCRIPT_MAIN_NAME
export SCRIPT_MAIN_DIR
export SCRIPT_MAIN_EXE

export SCRIPT_CURRENT_PATH

_set_scriptcurrent
